export  const images = {
  img_about: require("./about.jpg"),
  img_beard_trim: require("./beard-trim.png"),
  img_carousel_1: require("./carousel-1.jpg"),
  img_carousel_2: require("./carousel-2.jpg"),
  img_hair_dyeing: require("./hair-dyeing.png"),
  img_haircut: require("./haircut.png"),
  img_mans_shave: require("./mans-shave.png"),
  img_mustache: require("./mustache.png"),
  img_open: require("./open.jpg"),
  img_price: require("./price.jpg"),
  img_stacking: require("./stacking.png"),
  img_team_1: require("./team-1.jpg"),
  img_team_2: require("./team-2.jpg"),
  img_team_3: require("./team-3.jpg"),
  img_team_4: require("./team-4.jpg"),
  img_testimonial_1: require("./testimonial-1.jpg"),
  img_testimonial_2: require("./testimonial-2.jpg"),
  img_testimonial_3: require("./testimonial-3.jpg"),
};
   
